name: Deploy to Render

on:
  release:
    types: [published]  # Cuando se crea una release nueva

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST https://api.render.com/deploy/srv-xxxxxxxxxx?key=YOUR_API_KEY
