name: Deploy to Render

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Deploy Hook
      run: |
        curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
