name: Django Tests

on:
    pull_request:
        branch: [main]

jobs:
    tests:
        name: tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
                  cache: 'pip'
            - run: pip install -r requirements-dev.txt

            - name: Install system dependencies for browsers
              run: |
                sudo apt update
                sudo apt install -y \
                  libasound2t64 \
                  libnss3 \
                  libxss1 \
                  libatk-bridge2.0-0 \
                  libgtk-3-0 \
                  libxcomposite1 \
                  libxrandr2 \
                  libgbm1 \
                  libpango-1.0-0 \
                  libcups2 \
                  libatk1.0-0 \
                  libpangocairo-1.0-0 \
                  libxdamage1 \
                  libxfixes3

            - name: Install playwright
              run: python -m playwright install firefox

            - name: Run unit and integration tests
              run: coverage run --source="./app" --omit="./app/migrations/**" manage.py test app

            - name: Run e2e tests
              run: python manage.py test functional_tests